## START: Set by rpmautospec
## (rpmautospec version 0.8.3)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 1;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

Name:       quester
Version:    0.1.0
Release:    %{autorelease}
Summary:    A modern, visually rich MPD client built with Qt 6 and QML

License:    MIT
URL:        https://codeberg.org/anoraktrend/quester
Source:     %{url}/archive/%{version}.tar.gz#/quester-%{version}.tar.gz

BuildRequires:  cmake
BuildRequires:  gcc-c++
BuildRequires:  kf6-rpm-macros
BuildRequires:  qt6-qtbase-devel
BuildRequires:  qt6-qtdeclarative-devel
BuildRequires:  qt6-qtmultimedia-devel
BuildRequires:  libmpdclient-devel
BuildRequires:  highway-devel
BuildRequires:  fftw-devel
BuildRequires:  libprojectM-devel
BuildRequires:  pipewire-devel
BuildRequires:  pulseaudio-libs-devel
BuildRequires:  extra-cmake-modules


%description
Quester is a desktop client for the Music Player Daemon (MPD). It provides a fluid user interface focused on album art and visual feedback. Built using C++ and Qt Quick (QML), it aims to offer a lightweight yet visually appealing way to browse and play your music library.

%prep
%autosetup -n quester

%conf
%cmake

%build
%cmake_build

%install
%cmake_install

%files
%{_bindir}/quester
%{_sysconfdir}/config/Quester/presets/presets.json
%{_datadir}/Quester/presets/presets.json
%{_datadir}/applications/quester.desktop
%{_datadir}/icons/hicolor/scalable/apps/quester.svg

%changelog
## START: Generated by rpmautospec
* Mon Feb 16 2026 SED4906 - 0.1.0-1
- Initial packaging
## END: Generated by rpmautospec
