## START: Set by rpmautospec
## (rpmautospec version 0.8.3)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 1;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

Name:       windowtolayer
Version:    0.3.0
Release:    %{autorelease}
Summary:    Display existing (xdg-shell) Wayland applications as a wallpaper (layer-shell) instead

License:    GPLv3
URL:        https://gitlab.freedesktop.org/mstoeckl/windowtolayer
Source:     %{url}/-/archive/v0.3.0/windowtolayer-v0.3.0.tar.gz#/windowtolayer-0.3.0.tar.gz

BuildRequires:  gcc
BuildRequires:  cargo-rpm-macros
BuildRequires:  rustfmt
BuildRequires:  pkgconfig(wayland-client) >= 1.20.0
BuildRequires:  pkgconfig(wayland-protocols) >= 1.25
BuildRequires:  pkgconfig(wayland-scanner)

%generate_buildrequires
%cargo_generate_buildrequires

%description
This program transforms individual Wayland clients, which use the xdg-shell
protocol to display windows, into clients that use the wlr-layer-shell protocol
to render as a wallpaper. Note that wlr-layer-shell is only supported by some
compositors (like KWin, and those based on wlroots.)

%prep
%autosetup -n windowtolayer-v0.3.0
%cargo_prep

%build
%cargo_build

%install
mkdir -p %{buildroot}%{_bindir}
cp target/rpm/windowtolayer %{buildroot}%{_bindir}/

%files
%{_bindir}/%{name}

%changelog
## START: Generated by rpmautospec
* Mon Feb 16 2026 SED4906 - 0.3.0-1
- Initial packaging
## END: Generated by rpmautospec
