## START: Set by rpmautospec
## (rpmautospec version 0.8.3)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 1;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

Name:       wscreensaver
Version:    2023.12.27
Release:    %{autorelease}
Summary:    Fork of xscreensaver to draw animated wallpapers on Wayland

License:    MIT
URL:        https://git.sr.ht/~mstoeckl/wscreensaver
Source:     %{url}/archive/2155bb8fa348785842b75843e7d0dee4ee00fb90.tar.gz#/wscreensaver-2155bb8fa348785842b75843e7d0dee4ee00fb90.tar.gz

BuildRequires:  gcc
#BuildRequires:  gnupg2
BuildRequires:  meson >= 0.59.0
BuildRequires:  pam-devel
#BuildRequires:  pkgconfig(cairo)
#BuildRequires:  pkgconfig(gdk-pixbuf-2.0)
BuildRequires:  pkgconfig(wayland-client) >= 1.20.0
BuildRequires:  pkgconfig(wayland-protocols) >= 1.25
BuildRequires:  pkgconfig(wayland-scanner)
#BuildRequires:  pkgconfig(xkbcommon)
BuildRequires:  intltool
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  libjpeg-turbo-devel
BuildRequires:  gtk3-devel
BuildRequires:  libX11-devel
BuildRequires:  libXi-devel
BuildRequires:  libXt-devel

%description
This is an experimental fork of xscreensaver which makes it possible to run
some of the hacks as animated wallpapers on Wayland compositors that support
wlr-layer-shell.

%prep
%autosetup -n wscreensaver-2155bb8fa348785842b75843e7d0dee4ee00fb90

%conf
./configure --build=x86_64-redhat-linux --host=x86_64-redhat-linux --program-prefix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/bin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --runstatedir=/run --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info

%build
%make_build
cd wayland
%meson
%meson_build

%install
cd wayland
%meson_install

%files
/usr/bin/xscreensaver-*

%changelog
## START: Generated by rpmautospec
* Mon Feb 09 2026 SED4906 - 2023.12.27-1
- Initial packaging
## END: Generated by rpmautospec
